version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - npm install -g terser@5.16.1 imagemin-cli@5.0.0 html-minifier@4.0.0 sass@1.56.1 --unsafe-perm=true --allow-root
  pre_build:
    commands:
      - mkdir build
      - mkdir build/scripts
      - mkdir build/assets
      - mkdir build/styles
  build:
    commands:
      - imagemin src/assets/* --out-dir=build/assets
      - terser src/scripts/vr.js --compress | terser --mangle --output=build/scripts/vr.min.js
      - terser src/scripts/index.js --compress | terser --mangle --output=build/scripts/index.min.js
      - html-minifier --collapse-whitespace --remove-comments --remove-redundant-attributes --remove-script-type-attributes --remove-tag-whitespace --use-short-doctype -o build/index.html src/pages/index.html
      - html-minifier --collapse-whitespace --remove-comments --remove-redundant-attributes --remove-script-type-attributes --remove-tag-whitespace --use-short-doctype -o build/vr.html src/pages/vr.html
      - sass src/styles:build/styles --style compressed
artifacts:
  name: BuildOutput
  files:
    - '**/*'
  discard-paths: no
  base-directory: 'build'
