version: 0.2

env:
  variables:
    ELM_VERSION: "0.19.1"

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - npm install -g uglify-js imagemin-cli html-minifier
      - mkdir bin
      - cd bin
      - curl -L -o elm.gz https://github.com/elm/compiler/releases/download/${ELM_VERSION}/binary-for-linux-64-bit.gz
      - gunzip elm.gz
      - chmod +x elm
      - sudo mv elm /usr/local/bin/
    finally:
      - cd ${CODEBUILD_SRC_DIR}
  pre_build:
    commands:
      - mkdir build
  build:
    commands:
      - elm make --optimize --output=build/app.js src/Main.elm
      - uglifyjs build/app.js --compress 'pure_funcs="F2,F3,F4,F5,F6,F7,F8,F9,A2,A3,A4,A5,A6,A7,A8,A9",pure_getters,keep_fargs=false,unsafe_comps,unsafe' | uglifyjs --mangle --output=build/app.min.js
      - rm build/app.js
      - imagemin src/assets/* --out-dir=build/assets
      - html-minifier --collapse-whitespace --remove-comments --remove-optional-tags --remove-redundant-attributes --remove-script-type-attributes --remove-tag-whitespace --use-short-doctype -o build/index.html index.html
artifacts:
  name: BuildOutput
  files:
    - '**/*'
  discard-paths: no
  base-directory: 'build'